config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  get 'secret', to: 'pages#secret'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  validates :title, :instructions, :prep_time, :cook_time, presence: true
  validates :prep_time, :cook_time, comparison: { greater_than: 0 }

  has_many :recipe_tags, dependent: :destroy
  has_many :tags, through: :recipe_tags

  accepts_nested_attributes_for :recipe_tags, allow_destroy: true

end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag

  validates :tag_id, uniqueness: { scope: :recipe_id }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tags, dependent: :destroy
  has_many :recipes, through: :recipe_tags

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable
  validates :given_name, :family_name, presence: true

  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, 
      keys: [:given_name, :family_name]
      )
  devise_parameter_sanitizer.permit(
      :account_update, 
      keys: [:given_name, :family_name]
      )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :secret
  def home
  end
  def home
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :check_private_access!, only: [:show]
  before_action :authorize_user!, only: %i[edit update destroy] 

  # GET /recipes
  def index
    @recipes = Recipe.where(is_private: false)

    if user_signed_in?
      @recipes = @recipes.or(Recipe.where(user: current_user, is_private: true))
    end
  end
  
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: "Recipe was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "Recipe was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy!
    redirect_to recipes_url, notice: "Recipe was successfully destroyed.", status: :see_other
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :instructions, :prep_time, :cook_time, :is_private, :calories, tag_ids: [])
    end

  def check_private_access!
    # Check 1: Is it private? AND Check 2: Does the current user NOT own it?
    if @recipe.is_private? && @recipe.user != current_user
      redirect_to recipes_path, alert: "You are not authorized to view this private recipe."
    end
  end

    def authorize_user!
    unless @recipe.user == current_user
      redirect_to recipes_path, alert: "You are not authorized to modify this recipe."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Finance tracker</p>

<%= current_user.inspect %>
<% if user_signed_in? %>
  <%= button_to 'Log out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
  <%= link_to 'Register', new_user_registration_path %>
<% end %>

app/views/pages/secret.html.erb
Top secret page. 

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :instructions, style: "display: block" %>
    <%= form.text_area :instructions %>
  </div>

  <div>
    <%= form.label :prep_time, style: "display: block" %>
    <%= form.number_field :prep_time %>
  </div>

  <div>
    <%= form.label :cook_time, style: "display: block" %>
    <%= form.number_field :cook_time %>
  </div>

  <div>
    <%= form.label :is_private, style: "display: block" %>
    <%= form.check_box :is_private %>
  </div>

  <div>
    <%= form.label :calories, style: "display: block" %>
    <%= form.text_field :calories %>
  </div>

  <div>
    <%= form.label :tag_ids, "Select Tags", style: "display: block" %>
    <%= form.select :tag_ids, 
                   options_from_collection_for_select(Tag.all, :id, :name, @recipe.tag_ids),
                   { prompt: "Select one or more tags" },
                   { multiple: true, style: "display: block;" } 
  %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Title:</strong>
    <%= recipe.title %>
  </p>

  <p>
    <strong>Instructions:</strong>
    <%= recipe.instructions %>
  </p>

  <p>
    <strong>Prep time:</strong>
    <%= recipe.prep_time %>
  </p>

  <p>
    <strong>Cook time:</strong>
    <%= recipe.cook_time %>
  </p>

  <p>
    <strong>Is private:</strong>
    <%= recipe.is_private %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= recipe.calories %>
  </p>

  <div>
    <p><strong>Tags</strong></p>
    <% if recipe.tags.any? %>
      <p>
        <% recipe.tags.each do |tag| %>
          <span class="recipe-tag">
            <%= tag.name %>
          </span>
        <% end %>
      </p>
    <% end %>
  </div>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>